;; Copyright (c) 2026 Will Cohen
;;
;; Part of clj-native, under the Apache License v2.0 with LLVM Exceptions.
;; See LICENSE for license information.
;; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

(ns net.willcohen.native.gen-handler
  "Build-time generator. It emits a Worker-router ModuleHandler module from
   fndefs and library overrides.

   This generator is a JVM or babashka fn, and not a CLJS macro. Thus it can
   read the consumer fndefs through a deps.edn :local/root. A CLJS macro
   cannot do that, because of the squint user-space defmacro limitation."
  (:require [clojure.string :as str]))

(def ^:private required-override-keys
  [:overrides-import-path :runtime-import-path :exposed-methods])

(defn- check-required! [overrides]
  (doseq [k required-override-keys]
    (when (nil? (get overrides k))
      (throw (ex-info (str "gen-handler-source: missing required override key " k)
                      {:missing k :overrides-keys (vec (keys overrides))})))))

(defn- js-string-literal
  "Render a JS double-quoted string literal. This function escapes each
   backslash and each quote."
  [s]
  (let [s (name s)]
    (str "\""
         (-> s
             (str/replace "\\" "\\\\")
             (str/replace "\"" "\\\""))
         "\"")))

(defn- js-string-array [coll]
  (str "[" (str/join ", " (map js-string-literal coll)) "]"))

(defn- destroy-fns-from-fndefs [fndefs]
  (->> fndefs
       (filter (fn [[_ v]] (:destroy? v)))
       (map (comp name first))
       sort
       vec))

(def ^:private default-preamble
  (str "// Generated by clj-native gen-handler-source. Do not edit by hand;\n"
       "// changes will be overwritten on the next bb gen-handler run.\n"
       "//\n"
       "// Wires a hand-written overrides module (init, methods, fingerprint)\n"
       "// into clj-native's handler runtime, applying the busy/destroy\n"
       "// classification computed from the consumer's fndefs."))

(defn gen-handler-source
  "Generate a JS handler module source string.

   fndefs    A map of { fn-key -> { :rettype :argtypes :busy? :destroy? ... } }.
             When overrides omit :destroy-fns, gen-handler-source derives
             `destroyFns` from this map. `destroyFns` holds the C function
             names that the ccall dispatcher treats as teardown.

   overrides A map with these keys:
       :overrides-import-path  The module path of the hand-written overrides
                               .mjs.
       :runtime-import-path    The module path of the published handler
                               runtime.
       :exposed-methods        Method-name keywords. Each one wires
                               methods.<name> from the overrides module.
       :busy-methods           An optional subset with the busy
                               classification. A busy method increments a
                               counter on entry, and decrements it on exit.
                               The default is []. The runtime queue is fully
                               serial, thus this classification affects trace
                               fields only at this time. It stays accepted for
                               a future queue that serializes entry only.
       :destroy-methods        An optional subset with the destroy
                               classification. A destroy method is gated on
                               counter == 0. The default is []. It has the
                               same trace-only status as :busy-methods.
       :destroy-fns            Optional C function name strings. When they are
                               absent, gen-handler-source derives them from
                               the fndefs :destroy? flags.
       :fingerprint-fields     Optional init-arg names for the handler
                               fingerprint. With these names,
                               gen-handler-source emits a
                               byteLengthFingerprint call here. Without them,
                               it takes overrides.fingerprint. The first form
                               lets an overrides module import nothing from
                               the handler runtime. Refer to
                               :fingerprint-prefix.
       :fingerprint-prefix     An optional label for the fingerprint, so a
                               re-init error names the handler.
                               gen-handler-source ignores it without
                               :fingerprint-fields.
       :preamble               An optional string for the top of the output.

   gen-handler-source can generate the fingerprint, so no one must write it by
   hand. There is one reason for this. The overrides module of a handler stays
   external, while the bundler inlines this generated module. Thus an
   overrides module that imports the handler runtime gets a SECOND copy of
   that runtime, with its own logging state. The fingerprint here keeps the
   one import of the runtime in the one inlined module."
  [fndefs overrides]
  (check-required! overrides)
  (let [{:keys [overrides-import-path runtime-import-path
                exposed-methods busy-methods destroy-methods
                destroy-fns fingerprint-fields fingerprint-prefix
                preamble]} overrides
        busy-methods (or busy-methods [])
        destroy-methods (or destroy-methods [])
        destroy-fns (or destroy-fns (destroy-fns-from-fndefs fndefs))
        generated-fingerprint? (seq fingerprint-fields)
        method-bindings (->> exposed-methods
                             (map (fn [m]
                                    (let [n (name m)]
                                      (str "  " n ": overrides.methods." n ","))))
                             (str/join "\n"))]
    (str
     (or preamble default-preamble) "\n\n"
     "import { makeHandler"
     (when generated-fingerprint? ", byteLengthFingerprint")
     " } from '" runtime-import-path "';\n"
     "import * as overrides from '" overrides-import-path "';\n"
     "\n"
     "// Method classification. The handler runtime header says what it does.\n"
     "const busyMethods = " (js-string-array busy-methods) ";\n"
     "const destroyMethods = " (js-string-array destroy-methods) ";\n"
     "\n"
     "// C fnNames from the fndefs :destroy? flags. Nothing reads this.\n"
     "const destroyFns = " (js-string-array destroy-fns) ";\n"
     "\n"
     "const methods = {\n"
     method-bindings "\n"
     "};\n"
     "\n"
     (when generated-fingerprint?
       (str "// Init-arg fields this handler is cached on. Bytes contribute their\n"
            "// length, so a database costs one number rather than its contents.\n"
            "const fingerprint = byteLengthFingerprint(\n"
            "  " (js-string-array (map name fingerprint-fields)) ",\n"
            "  " (if fingerprint-prefix (str "'" fingerprint-prefix "'") "null") ",\n"
            ");\n"
            "\n"))
     "export const create = makeHandler({\n"
     "  init: overrides.init,\n"
     "  methods,\n"
     "  busyMethods,\n"
     "  destroyMethods,\n"
     "  fingerprint: " (if generated-fingerprint? "fingerprint" "overrides.fingerprint") ",\n"
     "});\n"
     "\n"
     "export default create;\n"
     "export { create as handler };\n"
     "export { destroyFns };\n"
     "\n"
     "// Module-level teardown for worker-router's coordinator shutdown, which\n"
     "// invokes `mod.destroy` (see worker-bootstrap loadAllHandlers) once per\n"
     "// worker when the pool terminates. Forwards to the overrides module's\n"
     "// destroy when it exports one, else undefined (worker-router guards with\n"
     "// `typeof mod.destroy === 'function'`). This is where a handler closes\n"
     "// nested resources the emscripten Module holds open, such as the\n"
     "// http-bridge fetch worker.\n"
     "//\n"
     "// A handler that exports no destroy is not a leak on node 26: terminate()\n"
     "// reaps a nested worker_thread, measured with sixteen pool workers and\n"
     "// requests in flight. Export one to close the resource on purpose.\n"
     "export const destroy = overrides.destroy;\n")))

(defn write-handler!
  "Invoke gen-handler-source. Then write the result to `out-path`, a string or
   a java.io.File. Returns the path. This is the entry point with side effects
   for bb tasks."
  [fndefs overrides out-path]
  (let [src (gen-handler-source fndefs overrides)]
    (spit out-path src)
    (str out-path)))
