;; Copyright (c) 2026 Will Cohen
;;
;; Part of clj-native, under the Apache License v2.0 with LLVM Exceptions.
;; See LICENSE for license information.
;; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

(ns net.willcohen.native.gen-handler
  "Build-time generator of a worker-router ModuleHandler module from fndefs
   and library overrides. It runs on the JVM or babashka, because a squint
   user-space macro cannot read consumer fndefs through a deps.edn
   :local/root."
  (:require [clojure.string :as str]))

(def ^:private required-override-keys
  [:overrides-import-path :runtime-import-path :exposed-methods :fingerprint-fields])

(defn- check-required! [overrides]
  (doseq [k required-override-keys]
    (when (nil? (get overrides k))
      (throw (ex-info (str "gen-handler-source: missing required override key " k)
                      {:missing k :overrides-keys (vec (keys overrides))})))))

(defn- js-string-literal
  [s]
  (let [s (name s)]
    (str "\""
         (-> s
             (str/replace "\\" "\\\\")
             (str/replace "\"" "\\\""))
         "\"")))

(defn- js-string-array [coll]
  (str "[" (str/join ", " (map js-string-literal coll)) "]"))

(defn- destroy-fns-from-fndefs [fndefs]
  (->> fndefs
       (filter (fn [[_ v]] (:destroy? v)))
       (map (comp name first))
       sort
       vec))

(defn gen-handler-source
  "Return the source of a JS handler module.

   fndefs     {fn-key fn-def}. Only :destroy? of a fn-def is read.
   overrides  Keys:
     :overrides-import-path  Required. Path of the overrides .mjs.
     :runtime-import-path    Required. Path of the handler runtime.
     :exposed-methods        Required. Method keywords, each mapped to
                             overrides.methods.<name>.
     :fingerprint-fields     Required. Init-arg names for the
                             byteLengthFingerprint of the handler.
     :busy-methods           Subset of :exposed-methods, disjoint from
                             :destroy-methods. Default [].
     :destroy-methods        Subset of :exposed-methods. Default [].
     :destroy-fns            C fn names. Default: fndefs keys with :destroy?.
     :fingerprint-prefix     Fingerprint label for re-init errors.

   The busy and destroy classes pick trace events only, because the runtime
   queue is serial. The fingerprint is generated here because the bundler
   inlines this module but not the overrides module, so an overrides module
   that imports the runtime gets a second copy with its own logging state.

   The overrides module can export `destroy`, which worker-router calls once
   per worker when the pool terminates, to close resources that the
   emscripten Module holds open, such as the http-bridge fetch worker."
  [fndefs overrides]
  (check-required! overrides)
  (let [{:keys [overrides-import-path runtime-import-path
                exposed-methods busy-methods destroy-methods
                destroy-fns fingerprint-fields fingerprint-prefix]} overrides
        busy-methods (or busy-methods [])
        destroy-methods (or destroy-methods [])
        destroy-fns (or destroy-fns (destroy-fns-from-fndefs fndefs))
        method-bindings (->> exposed-methods
                             (map (fn [m]
                                    (let [n (name m)]
                                      (str "  " n ": overrides.methods." n ","))))
                             (str/join "\n"))]
    (str
     "// Generated by clj-native gen-handler-source. Do not edit.\n\n"
     "import { makeHandler, byteLengthFingerprint } from '" runtime-import-path "';\n"
     "import * as overrides from '" overrides-import-path "';\n"
     "\n"
     "const busyMethods = " (js-string-array busy-methods) ";\n"
     "const destroyMethods = " (js-string-array destroy-methods) ";\n"
     "\n"
     "// C fnNames from the fndefs :destroy? flags. Nothing reads this.\n"
     "const destroyFns = " (js-string-array destroy-fns) ";\n"
     "\n"
     "const methods = {\n"
     method-bindings "\n"
     "};\n"
     "\n"
     "const fingerprint = byteLengthFingerprint(\n"
     "  " (js-string-array fingerprint-fields) ",\n"
     "  " (if fingerprint-prefix (js-string-literal fingerprint-prefix) "null") ",\n"
     ");\n"
     "\n"
     "export const create = makeHandler({\n"
     "  init: overrides.init,\n"
     "  methods,\n"
     "  busyMethods,\n"
     "  destroyMethods,\n"
     "  fingerprint,\n"
     "});\n"
     "\n"
     "export default create;\n"
     "export { destroyFns };\n"
     "\n"
     "export const destroy = overrides.destroy;\n")))

(defn write-handler!
  "Write the gen-handler-source output to `out-path`, a string or File.
   Returns the path as a string."
  [fndefs overrides out-path]
  (let [src (gen-handler-source fndefs overrides)]
    (spit out-path src)
    (str out-path)))
